DELETE FROM login_info;

INSERT INTO login_info VALUES (1, 'testmail@gmail.com', 'main');
INSERT INTO login_info VALUES (2, 'test.mail@gmail.com', 'mainTwo');

DELETE FROM gta_character;

INSERT INTO gta_character VALUES (1,
                                  'Claude Speed',
                                  'GTA III',
                                  'Claude is a calm and serious man who appears almost emotionless regardless of the situation, aside from a slight smirk and usually a glare, seemingly taking everything in stride. Provided he is paid for his services, he will take orders from his bosses without reluctance or complaint, usually giving a nod to show that he understands, and doesnt respond even when he is scolded or shouted at by his bosses for doing something wrong. He also prostrates to his bosses if required, for example, Kenji Kasen.',
                                  'https://gta.fandom.com/wiki/Claude',
                                  'https://www.rockstargames.com/games/grandtheftauto3',
                                  0,
                                  0,
                                  0,
                                  0);
INSERT INTO gta_character VALUES (2,
                                  'Tommy Vercetti',
                                  'GTA Vice City',
                                  'Thomas Tommy Vercetti is depicted as both intelligent and temperamental. He is easily angered and quick to resort to violence. He does not hesitate to kill, though many of his victims are trying to kill Tommy, or have done something that guaranteed their deaths. However, Tommy often shows care and sensitivity towards characters like Mercedes Cortez and especially Earnest Kelly, viewing Kelly as a father figure due to his own father working in a print works, and showing anger and concern when Kelly is injured by Sonnys hitmen.',
                                  'https://gta.fandom.com/wiki/Tommy_Vercetti',
                                  'https://www.rockstargames.com/games/vicecity',
                                  1,
                                  1,
                                  1,
                                  1);
INSERT INTO gta_character VALUES (3,
                                  'Carl Johnson',
                                  'GTA San Andreas',
                                  'CJ is markedly different from the previous playable characters in the Grand Theft Auto series. While Claude and Tommy Vercetti are both depicted as completely heartless and feeling no regret for all of the people that they kill, CJ is depicted as having a considerably less violent personality, occasionally giving his targets a chance to redeem themselves. An example is his failed attempt at convincing Eddie Pulaski to see that he was no more than Tenpennys pawn in the mission High Noon. Furthermore, CJ displays genuine remorse for having to kill Ryder and Big Smoke, who he considered close friends. However, CJ has no problem with killing members of other gangs, and willfully slaughters any that get in his way of reclaiming Grove Street Family turf or try to sabotage his businesses, though in return, the gangsters are trying to kill CJ also.',
                                  'https://gta.fandom.com/wiki/Carl_Johnson',
                                  'https://www.rockstargames.com/games/sanandreas',
                                  2,
                                  2,
                                  2,
                                  2);
INSERT INTO gta_character VALUES (4,
                                  'Toni Cipriani',
                                  'GTA Liberty City Stories',
                                  'Toni is in some ways similar to Tommy Vercetti, and his behavior in scenes of the game suggest that he is very loyal, but very easy to irritate (of course, this may be in part of that he is surrounded by such strange people, for instance, Maria Latore, Joseph Daniel OToole and Donald Love). When enraged, Toni is capable of practicing extremely violent acts (like using an axe to kill Giovanni Casa and cut his body into small pieces), but he also seems to feel remorseful at times (like when he goes to the Cathedral to make a confession). However, like many other GTA protagonists, he too shows very little hesitation in killing anyone standing in his way and occasionally mocks them. Toni also believes that people should show proper respect to their parents, as seen in the mission Hot Wheels, when he berates Vincenzo Cilli for receiving oral sex from a prostitute named Cheryl while talking to his mother, and how he desperately tries to please his mother.',
                                  'https://gta.fandom.com/wiki/Toni_Cipriani',
                                  'https://www.rockstargames.com/games/libertycitystories',
                                  3,
                                  3,
                                  3,
                                  3);
INSERT INTO gta_character VALUES (5,
                                  'Victor Vance',
                                  'GTA Vice City Stories',
                                  'Victor is a tough and sometimes strict person when it comes to the crimes he unwillingly commits. Vic is also shown to be a short-tempered man, easily becoming provoked upon watching the foolish actions made by other characters, most notably his younger brother Lance, and is more rational than his easy-going, cheerful, yet equally short-tempered younger brother. Despite being involved in drug smuggling, Vic has shown a dislike for them, believing that they destroy peoples lives, and does not willingly use them recreationally, much like GTA San Andreas protagonist Carl Johnson.',
                                  'https://gta.fandom.com/wiki/Victor_Vance',
                                  'https://www.rockstargames.com/games/vicecitystories',
                                  4,
                                  4,
                                  4,
                                  4);
INSERT INTO gta_character VALUES (6,
                                  'Niko Bellic',
                                  'GTA IV',
                                  'Niko is very protective of his family and loved ones, particularly his cousin Roman, whom Niko constantly has to worry about due to his gambling habit. Nikos bitterness at the murder of his friends during the war has consumed him, and he is unable to let it go, taking on several highly dangerous jobs merely to enable his quest for vengeance. Nikos business-like manner usually leads him to behave more maturely and cautiously than his acquaintances, although with acquaintances like Brucie Kibbutz, Bernie Crane and Roman, this is no surprise. He has an apparent distaste for illegal drugs, much like Carl Johnson and Victor Vance. Niko also exhibits dislike for American conservative politicians, whom he considers to be hypocrites.',
                                  'https://gta.fandom.com/wiki/Niko_Bellic',
                                  'https://www.rockstargames.com/games/IV',
                                  5,
                                  5,
                                  5,
                                  5);
INSERT INTO gta_character VALUES (7,
                                  'Johnny Klebitz',
                                  'GTA The Lost and Damned',
                                  'Johnny is relaxed and laid back most of the time. He wants to think all plans and actions through and doesnt want to make any risky decisions. He is very easily angered and will become aggressive and violent when provoked. He shows some hesitation about killing people whom he thinks deserve it. He also has his limit about killing. He asks Elizabeta if killing so many people is really necessary. Overall, Johnnys attitude about murder seems to be that he is capable of doing so in cold blood but believes that the murder should be justified. Johnny will always carry out orders given to him even if he disagrees with them, but will vent his frustration when doing so. Later in the game, Johnny claims that he has given up on faith and instead believes in religion. Johnny has an anti-war and anti-politics stance, claiming both exist to "make the fat cats fatter".',
                                  'https://gta.fandom.com/wiki/Johnny_Klebitz',
                                  'https://www.rockstargames.com/thelostanddamned',
                                  6,
                                  6,
                                  6,
                                  6);
INSERT INTO gta_character VALUES (8,
                                  'Luis Fernando Lopez',
                                  'GTA The Ballad of Gay Tony',
                                  'Luis is a relatively reserved character, as he rarely demonstrates his emotions or feelings. Despite this, Luis does care for his mother and friends as he was visually struggling to restrain his anger toward Mr. Santo because of his threatening behaviour towards his mother. Luis is very sarcastic and unafraid to stand up to people if he deems it necessary. His reserved, level-headed personality makes him a perfect foil to the flamboyant, impulsive Tony.',
                                  'https://gta.fandom.com/wiki/Luis_Fernando_Lopez',
                                  'https://www.rockstargames.com/theballadofgaytony',
                                  7,
                                  7,
                                  7,
                                  7);
INSERT INTO gta_character VALUES (9,
                                  'Franklin Clinton',
                                  'GTA V',
                                  'Franklin is described as ambitious, but perhaps to a fault, and very eager to take on new illegal challenges. He is also described as calm, smart, rational and a "logical way of showing a young man with a lot of hope", with Dan Houser claiming that this would be a nice contrast from Michael. He is also a person that, even though hes being mentored by Michael in crime, mentors Michael in life. This helps build up the Father-Son relationship between the two, in contrast to their own actual father-son relationships (Franklins father abandoned him before his birth and Michaels relationship with Jimmy soured years ago).',
                                  'https://gta.fandom.com/wiki/Franklin_Clinton',
                                  'https://www.rockstargames.com/gta-v',
                                  8,
                                  8,
                                  8,
                                  8);
INSERT INTO gta_character VALUES (10,
                                  'Michael De Santa',
                                  'GTA V',
                                  'Michael is a very muddled person, even confused by his "good and evil" personalities. He spends an uncommon amount of time in his head, where he can comfortably think or reminisce about certain things or aspects that give him a brief moment of nostalgia from his glory days. Nevertheless, it also constrains him into a world of wistfulness and bewilderment as he ponders the reason why things arent going in the direction he planned it would. Michael has an obsession for materialistic appearance and images, making it the main reason for why he dreamt of living out his Vinewood Dream with his family. He claims to Franklin that he has lived a repeated pattern of "Chase things, get em, hate em".',
                                  'https://gta.fandom.com/wiki/Michael_De_Santa',
                                  'https://www.rockstargames.com/gta-v',
                                  9,
                                  9,
                                  9,
                                  9);
INSERT INTO gta_character VALUES (11,
                                  'Trevor Philips',
                                  'GTA V',
                                  'Trevor has been described as a difficult person to deal with: extreme, impetuous, vengeful, psychopathic, unhinged, unpredictable, untamed, infamous, homicidal, and prone to violent outbursts and destructive rampages. He does everything in a sociopathic and relentless manner, (much different from Michael). Although Trevor is like this, he is honest about it and will never show hypocrisy. He has his own charm along with his own principles. However, Dan Houser has confirmed that Trevor "may not be all he seems" and is still "too horrible" to be a hero of any kind. He is also quite insecure about being born in Canada, and takes offense to people mocking his accent. Almost all of his Rampages are caused by Trevor flying into rage over being mocked over his Canadian accent.',
                                  'https://gta.fandom.com/wiki/Trevor_Philips',
                                  'https://www.rockstargames.com/gta-v',
                                  10,
                                  10,
                                  10,
                                  10);